USE [master]
GO
/****** Object:  Database [MyStock]    Script Date: 24/02/2023 10:10:10 AM ******/
CREATE DATABASE [MyStock]
GO
ALTER DATABASE [MyStock] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MyStock].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MyStock] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MyStock] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MyStock] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MyStock] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MyStock] SET ARITHABORT OFF 
GO
ALTER DATABASE [MyStock] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MyStock] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MyStock] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MyStock] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MyStock] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MyStock] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MyStock] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MyStock] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MyStock] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MyStock] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MyStock] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MyStock] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MyStock] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MyStock] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MyStock] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MyStock] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MyStock] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MyStock] SET RECOVERY FULL 
GO
ALTER DATABASE [MyStock] SET  MULTI_USER 
GO
ALTER DATABASE [MyStock] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MyStock] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MyStock] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MyStock] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MyStock] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [MyStock] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'MyStock', N'ON'
GO
ALTER DATABASE [MyStock] SET QUERY_STORE = OFF
GO
USE [MyStock]
GO
/****** Object:  Table [dbo].[Cars]    Script Date: 24/02/2023 10:10:10 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cars](
	[CarID] [int] NOT NULL,
	[CarName] [varchar](50) NULL,
	[Manufacturer] [varchar](50) NULL,
	[Price] [money] NULL,
	[ReleasedYear] [int] NULL,
 CONSTRAINT [PK_Cars] PRIMARY KEY CLUSTERED 
(
	[CarID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[Cars] ([CarID], [CarName], [Manufacturer], [Price], [ReleasedYear]) VALUES (1, N'Accord', N'Honda Motor Company', 24970.0000, 2021)
GO
INSERT [dbo].[Cars] ([CarID], [CarName], [Manufacturer], [Price], [ReleasedYear]) VALUES (2, N'Clarity', N'Honda Motor Company', 85000.0000, 2021)
GO
INSERT [dbo].[Cars] ([CarID], [CarName], [Manufacturer], [Price], [ReleasedYear]) VALUES (3, N'BMW 8 Series', N'BMW', 140000.0000, 2023)
GO
INSERT [dbo].[Cars] ([CarID], [CarName], [Manufacturer], [Price], [ReleasedYear]) VALUES (4, N'Audi A6', N'Audi', 24970.0000, 2020)
GO
INSERT [dbo].[Cars] ([CarID], [CarName], [Manufacturer], [Price], [ReleasedYear]) VALUES (5, N'Accord', N'Audi', 24970.0000, 2021)
GO
USE [master]
GO
ALTER DATABASE [MyStock] SET  READ_WRITE 
GO
